(function(){var V=function(){function l(a){var b=[];b[a-1]=void 0;return b}function G(a,b){return K(a[0]+b[0],a[1]+b[1])}function M(a,b){var c=E(a)&E(b);var d=c;0>c&&(d+=4294967296);return[d,4294967296*(~~Math.max(Math.min(a[1]/4294967296,2147483647),-2147483648)&~~Math.max(Math.min(b[1]/4294967296,2147483647),-2147483648))]}function N(a,b){if(a[0]==b[0]&&a[1]==b[1])return 0;var c=0>a[1];var d=0>b[1];return c&&!d?-1:!c&&d?1:0>K(a[0]-b[0],a[1]-b[1])[1]?-1:1}function K(a,b){b%=1.8446744073709552E19;
a%=1.8446744073709552E19;var c=b%4294967296;var d=4294967296*Math.floor(a/4294967296);b=b-c+d;for(a=a-d+c;0>a;)a+=4294967296,b-=4294967296;for(;4294967295<a;)a-=4294967296,b+=4294967296;for(b%=1.8446744073709552E19;0x7fffffff00000000<b;)b-=1.8446744073709552E19;for(;-9223372036854775808>b;)b+=1.8446744073709552E19;return[a,b]}function J(a){return 0<=a?[a,0]:[a+4294967296,-4294967296]}function E(a){return 2147483648<=a[0]?~~Math.max(Math.min(a[0]-4294967296,2147483647),-2147483648):~~Math.max(Math.min(a[0],
2147483647),-2147483648)}function ba(a){return 30>=a?1<<a:ba(30)*ba(a-30)}function ua(a,b){b&=63;if(a[0]==va[0]&&a[1]==va[1])return b?I:a;if(0>a[1])throw Error("Neg");var c=ba(b);var d=a[1]*c%1.8446744073709552E19;var e=a[0]*c;c=e-e%4294967296;d+=c;0x7fffffffffffffff<=d&&(d-=1.8446744073709552E19);return[e-c,d]}function wa(a,b){var c=ba(b&63);return K(Math.floor(a[0]/c),a[1]/c)}function xa(a,b){a.D=b;a.pa=0;a.count=b.length;return a}function O(a){return a.pa>=a.count?-1:a.D[a.pa++]&255}function ya(a){a.D=
new Uint8Array(32);a.count=0;return a}function ca(a){var b=a.D;if(b instanceof Uint8Array){b=new Uint8Array(a.count);var c=a.D;a=a.count;for(var d=0;d<a;++d)b[d]=c[d]}else b.length=a.count;return b}function za(a,b){if(a.D instanceof Uint8Array&&a.count==a.D.length){var c=a.D;a.D=new Uint8Array(c.length<<1);a.D.set(c)}a.D[a.count++]=b<<24>>24}function na(a,b,c,d,e){if(c instanceof Uint8Array&&d+e>c.length){var f=c;c=new Uint8Array(d+e);c.set(f)}for(f=0;f<e;++f)c[d+f]=a[b+f];return c}function Aa(a,
b,c){a.oa=ya({});var d=xa({},b),e=a.oa,f=J(b.length);if(0>N(f,da))throw Error("invalid length "+f);a.La=f;b={};var g;b.N=l(4);b.a=[];b.h={};b.G=l(192);b.M=l(12);b.ia=l(12);b.Fa=l(12);b.ib=l(12);b.ua=l(192);b.Ga=[];b.nb=l(114);b.$a=U({},4);b.va=Ba({});b.U=Ba({});b.ga={};b.K=[];b.ya=[];b.eb=[];b.Cb=l(16);b.g=l(4);b.R=l(4);b.dc=[I];b.ic=[I];b.finished=[0];b.zb=l(5);b.ec=l(128);b.Kb=0;b.Xa=1;b.wa=0;b.Mb=-1;for(g=b.ha=0;4096>g;++g)b.a[g]={};for(g=0;4>g;++g)b.Ga[g]=U({},6);g=1<<c.da;b.Va=g;for(var h=0;g>
1<<h;++h);b.Gb=2*h;b.H=c.aa;g=b.Xa;b.Xa=c.ba;b.f&&g!=b.Xa&&(b.Fb=-1,b.f=null);b.Ob=0;b.Nb=3;b.Ha=2;b.T=3;b.gc="undefined"==typeof V.jc;b.zb[0]=9*(5*b.Ha+b.Ob)+b.Nb<<24>>24;for(c=0;4>c;++c)b.zb[1+c]=b.Va>>8*c<<24>>24;e.D=na(b.zb,0,e.D,e.count,5);e.count+=5;for(c=0;64>c;c+=8)za(e,E(wa(f,c))&255);b.kb=0;b.hb=d;b.fb=0;b.f||(d={},f=4,b.Xa||(f=2),d.Da=2<f,d.Da?(d.ma=0,d.qb=4,d.Ba=66560):(d.ma=2,d.qb=3,d.Ba=0),b.f=d);d=b.ga;f=b.Ob;c=b.Nb;if(null==d.ca||d.O!=c||d.na!=f)for(d.na=f,d.wb=(1<<f)-1,d.O=c,c=1<<
d.O+d.na,d.ca=l(c),f=0;f<c;++f)g={},g.Ma=l(768),d.ca[f]=g;if(b.Va!=b.Fb||b.Mb!=b.H){d=b.f;f=b.Va;c=b.H;if(1073741567>f){d.Eb=16+(c>>1);h=f+4096;g=c+274;d.fc=h;d.Jb=g;h=h+g+(~~((f+4096+c+274)/2)+256);if(null==d.c||d.Ta!=h)d.c=null,d.Ta=h,d.c=l(d.Ta);d.mb=d.Ta-g;d.Ya=c;c=f+1;d.S!=c&&(d.s=l(2*(d.S=c)));c=65536;d.Da&&(c=f-1,c|=c>>1,c|=c>>2,c|=c>>4,c=(c|c>>8)>>1|65535,16777216<c&&(c>>=1),d.Hb=c,++c,c+=d.Ba);c!=d.Ib&&(d.L=l(d.Ib=c))}b.Fb=b.Va;b.Mb=b.H}b.h.fa=e;b.i=0;for(e=b.za=0;4>e;++e)b.N[e]=0;e=b.h;
e.ob=I;e.W=I;e.Range=-1;e.Ua=1;e.Db=0;y(b.G);y(b.ua);y(b.M);y(b.ia);y(b.Fa);y(b.ib);y(b.nb);e=b.ga;f=1<<e.O+e.na;for(d=0;d<f;++d)y(e.ca[d].Ma);for(e=0;4>e;++e)y(b.Ga[e].A);Ca(b.va,1<<b.Ha);Ca(b.U,1<<b.Ha);y(b.$a.A);b.jb=0;b.lb=0;b.Y=0;b.I=0;Da(b);Ea(b);b.va.Ia=b.H+1-2;Fa(b.va,1<<b.Ha);b.U.Ia=b.H+1-2;Fa(b.U,1<<b.Ha);b.l=I;void 0;e={};e.$=b;e.V=null;e.Ja=1;a.la=e;return a}function Ga(a,b){a.oa=ya({});var c=xa({},b),d=a.oa,e="",f,g=[];for(f=0;5>f;++f){var h=O(c);if(-1==h)throw Error("truncated input");
g[f]=h<<24>>24}var k={P:{},B:{}};k.Vb=l(192);k.Xb=l(12);k.Yb=l(12);k.Zb=l(12);k.$b=l(12);k.Wb=l(192);k.xb=l(4);k.bc=l(114);k.ac=W({},4);k.sb=Ha({});k.yb=Ha({});k.tb={};for(f=0;4>f;++f)k.xb[f]=W({},6);var n;if(5>g.length)f=0;else{var t=g[0]&255;h=~~(t/9);for(n=f=0;4>n;++n)f+=(g[1+n]&255)<<8*n;if(!(g=99999999<f)){t%=9;n=h%5;g=~~(h/5);if(8<t||4<n||4<g)g=0;else{h=k.tb;if(null==h.ca||h.O!=t||h.na!=n)for(h.na=n,h.wb=(1<<n)-1,h.O=t,n=1<<h.O+h.na,h.ca=l(n),t=0;t<n;++t){var m={};m.ab=l(768);h.ca[t]=m}g=1<<
g;Ia(k.sb,g);Ia(k.yb,g);k.hc=g-1;g=1}g=!g}if(g)f=0;else if(0>f)f=0;else{if(k.Sb!=f){k.Sb=f;k.Tb=Math.max(k.Sb,1);f=k.P;g=Math.max(k.Tb,4096);if(null==f.ta||f.ja!=g)f.ta=l(g);f.ja=g;f.b=0;f.m=0}f=1}}if(!f)throw Error("corrupted input");for(f=0;64>f;f+=8){h=O(c);if(-1==h)throw Error("truncated input");h=h.toString(16);1==h.length&&(h="0"+h);e=h+""+e}/^0+$|^f+$/i.test(e)?a.La=da:(e=parseInt(e,16),a.La=4294967295<e?da:J(e));e=a.La;k.B.fa=c;c=k.P;X(c);c.Aa=null;k.P.Aa=d;k.P.m=0;k.P.b=0;y(k.Vb);y(k.Wb);
y(k.Xb);y(k.Yb);y(k.Zb);y(k.$b);y(k.bc);d=k.tb;f=1<<d.O+d.na;for(c=0;c<f;++c)y(d.ca[c].ab);for(d=0;4>d;++d)y(k.xb[d].A);Ja(k.sb);Ja(k.yb);y(k.ac.A);d=k.B;d.F=0;d.Range=-1;for(c=0;5>c;++c)d.F=d.F<<8|O(d.fa);k.state=0;k.w=0;k.Oa=0;k.Pa=0;k.Ab=0;k.cc=e;k.l=I;k.bb=0;d={};d.V=k;d.$=null;d.Ja=1;a.la=d;return a}function F(a,b){return a.c[a.u+a.b+b]}function P(a,b,c,d){a.pb&&a.b+b+d>a.m&&(d=a.m-(a.b+b));++c;var e=a.u+a.b+b;for(b=0;b<d&&a.c[e+b]==a.c[e+b-c];++b);return b}function Y(a){return a.m-a.b}function Ka(a){if(!a.pb)for(;;){var b=
-a.u+a.Ta-a.m;if(!b)break;var c=a.Aa;var d=a.c;if(c.pa>=c.count)c=-1;else{b=Math.min(b,c.count-c.pa);if(na(c.D,c.pa,d,a.u+a.m,b)!==d)throw Error("buf changed");c.pa+=b;c=b}if(-1==c){a.xa=a.m;c=a.u+a.xa;c>a.mb&&(a.xa=a.mb-a.u);a.pb=1;break}a.m+=c;a.m>=a.b+a.Jb&&(a.xa=a.m-a.Jb)}}function La(a,b){a.u+=b;a.xa-=b;a.b-=b;a.m-=b}function ea(a){++a.J>=a.S&&(a.J=0);++a.b;if(a.b>a.xa){var b=a.u+a.b;if(b>a.mb){var c=a.u+a.b-a.fc;0<c&&--c;var d=a.u+a.m-c;for(b=0;b<d;++b)a.c[b]=a.c[c+b];a.u-=c}Ka(a)}1073741823==
a.b&&(b=a.b-a.S,Ma(a.s,2*a.S,b),Ma(a.L,a.Ib,b),La(a,b))}function Ma(a,b,c){var d;for(d=0;d<b;++d){var e=a[d]||0;e=e<=c?0:e-c;a[d]=e}}function Na(a,b){var c;do{if(a.b+a.Ya<=a.m)var d=a.Ya;else if(d=a.m-a.b,d<a.qb){ea(a);continue}var e=a.b>a.S?a.b-a.S:0;var f=a.u+a.b;if(a.Da){var g=fa[a.c[f]&255]^a.c[f+1]&255;var h=g&1023;a.L[h]=a.b;g^=(a.c[f+2]&255)<<8;h=g&65535;a.L[1024+h]=a.b;h=(g^fa[a.c[f+3]&255]<<5)&a.Hb}else h=a.c[f]&255^(a.c[f+1]&255)<<8;g=a.L[a.Ba+h];a.L[a.Ba+h]=a.b;var k=(a.J<<1)+1;var n=a.J<<
1;var t=c=a.ma;for(h=a.Eb;;){if(g<=e||0==h--){a.s[k]=a.s[n]=0;break}var m=a.b-g;m=(m<=a.J?a.J-m:a.J-m+a.S)<<1;var oa=a.u+g;var l=t<c?t:c;if(a.c[oa+l]==a.c[f+l]){for(;++l!=d&&a.c[oa+l]==a.c[f+l];);if(l==d){a.s[n]=a.s[m];a.s[k]=a.s[m+1];break}}(a.c[oa+l]&255)<(a.c[f+l]&255)?(a.s[n]=g,n=m+1,g=a.s[n],c=l):(a.s[k]=g,k=m,g=a.s[k],t=l)}ea(a)}while(0!=--b)}function X(a){var b=a.b-a.m;if(b){var c=a.Aa;c.D=na(a.ta,a.m,c.D,c.count,b);c.count+=b;a.b>=a.ja&&(a.b=0);a.m=a.b}}function Oa(a,b){var c=a.b-b-1;0>c&&
(c+=a.ja);return a.ta[c]}function ha(a){a-=2;return 4>a?a:3}function L(a){return 4>a?0:10>a?a-3:a-6}function ia(a){if(!a.Ja)throw Error("bad state");if(a.$){a:{var b=a.$,c=a.$.dc,d=a.$.ic,e=a.$.finished,f;c[0]=I;d[0]=I;e[0]=1;if(b.hb){b.f.Aa=b.hb;var g=b.f;g.u=0;g.b=0;g.m=0;g.pb=0;Ka(g);g.J=0;La(g,-1);b.kb=1;b.hb=null}if(!b.fb){b.fb=1;var h=g=b.l;if(h[0]==I[0]&&h[1]==I[1]){if(!Y(b.f)){pa(b,E(b.l));break a}qa(b);var k=E(b.l)&b.T;r(b.h,b.G,(b.i<<4)+k,0);b.i=L(b.i);var n=F(b.f,-b.I);Pa(Q(b.ga,E(b.l),
b.za),b.h,n);b.za=n;--b.I;b.l=G(b.l,Qa)}if(Y(b.f))for(;;){h=bb(b,E(b.l));n=b.ha;k=E(b.l)&b.T;var t=(b.i<<4)+k;if(1==h&&-1==n){r(b.h,b.G,t,0);n=F(b.f,-b.I);t=Q(b.ga,E(b.l),b.za);if(7>b.i)Pa(t,b.h,n);else{var m=F(b.f,-b.N[0]-1-b.I);var l;k=b.h;var v=m,q=n,x=l=1;for(f=7;0<=f;--f){var w=q>>f&1;m=x;l&&(l=v>>f&1,m+=1+l<<8,l=l==w);r(k,t.Ma,m,w);x=x<<1|w}}b.za=n;b.i=L(b.i)}else{r(b.h,b.G,t,1);if(4>n){if(r(b.h,b.M,b.i,1),n?(r(b.h,b.ia,b.i,1),1==n?r(b.h,b.Fa,b.i,0):(r(b.h,b.Fa,b.i,1),r(b.h,b.ib,b.i,n-2))):
(r(b.h,b.ia,b.i,0),1==h?r(b.h,b.ua,t,0):r(b.h,b.ua,t,1)),1==h?b.i=7>b.i?9:11:(ra(b.U,b.h,h-2,k),b.i=7>b.i?8:11),t=b.N[n],0!=n){for(;1<=n;--n)b.N[n]=b.N[n-1];b.N[0]=t}}else{r(b.h,b.M,b.i,0);b.i=7>b.i?7:10;ra(b.va,b.h,h-2,k);n-=4;k=sa(n);t=ha(h);Z(b.Ga[t],b.h,k);if(4<=k)if(f=(k>>1)-1,m=(2|k&1)<<f,w=n-m,14>k)for(t=b.nb,k=m-k-1,m=b.h,q=w,x=1,w=0;w<f;++w)v=q&1,r(m,t,k+x,v),x=x<<1|v,q>>=1;else Ra(b.h,w>>4,f-4),Sa(b.$a,b.h,w&15),++b.Bb;t=n;for(n=3;1<=n;--n)b.N[n]=b.N[n-1];b.N[0]=t;++b.Lb}b.za=F(b.f,h-1-
b.I)}b.I-=h;b.l=G(b.l,J(h));if(!b.I){128<=b.Lb&&Da(b);16<=b.Bb&&Ea(b);c[0]=b.l;h=b.h;d[0]=G(G(J(h.Ua),h.ob),[4,0]);if(!Y(b.f)){pa(b,E(b.l));break}h=b.l;if(0<=N(K(h[0]-g[0],h[1]-g[1]),[4096,0])){b.fb=0;e[0]=0;break}}}else pa(b,E(b.l))}}a.Rb=a.$.dc[0];a.$.finished[0]&&(b=a.$,Ta(b),b.h.fa=null,a.Ja=0)}else{a:{b=a.V;e=E(b.l)&b.hc;if(H(b.B,b.Vb,(b.state<<4)+e)){if(H(b.B,b.Xb,b.state))c=0,H(b.B,b.Yb,b.state)?(H(b.B,b.Zb,b.state)?(H(b.B,b.$b,b.state)?(d=b.Ab,b.Ab=b.Pa):d=b.Pa,b.Pa=b.Oa):d=b.Oa,b.Oa=b.w,
b.w=d):H(b.B,b.Wb,(b.state<<4)+e)||(b.state=7>b.state?9:11,c=1),c||(c=Ua(b.yb,b.B,e)+2,b.state=7>b.state?8:11);else if(b.Ab=b.Pa,b.Pa=b.Oa,b.Oa=b.w,c=2+Ua(b.sb,b.B,e),b.state=7>b.state?7:10,h=ja(b.xb[ha(c)],b.B),4<=h)if(d=(h>>1)-1,b.w=(2|h&1)<<d,14>h){e=b.w;g=b.bc;h=b.w-h-1;n=b.B;m=1;for(k=f=0;k<d;++k)t=H(n,g,h+m),m<<=1,m+=t,f|=t<<k;b.w=e+f}else{e=b.w;g=b.B;h=0;for(d-=4;0!=d;--d)g.Range>>>=1,n=g.F-g.Range>>>31,g.F-=g.Range&n-1,h=h<<1|1-n,g.Range&-16777216||(g.F=g.F<<8|O(g.fa),g.Range<<=8);b.w=e+(h<<
4);d=b.w;e=b.ac;g=b.B;t=1;for(n=k=0;n<e.ea;++n)h=H(g,e.A,t),t<<=1,t+=h,k|=h<<n;b.w=d+k;if(0>b.w){b=-1==b.w?1:-1;break a}}else b.w=h;if(0<=N(J(b.w),b.l)||b.w>=b.Tb){b=-1;break a}d=b.P;e=c;g=d.b-b.w-1;for(0>g&&(g+=d.ja);0!=e;--e)g>=d.ja&&(g=0),d.ta[d.b++]=d.ta[g++],d.b>=d.ja&&X(d);b.l=G(b.l,J(c));b.bb=Oa(b.P,0)}else{c=b.tb;c=c.ca[((E(b.l)&c.wb)<<c.O)+((b.bb&255)>>>8-c.O)];if(7>b.state){d=b.B;e=1;do e=e<<1|H(d,c.ab,e);while(256>e);c=e<<24>>24}else{d=b.B;e=Oa(b.P,b.w);n=1;do if(h=e>>7&1,e<<=1,g=H(d,c.ab,
(1+h<<8)+n),n=n<<1|g,h!=g){for(;256>n;)n=n<<1|H(d,c.ab,n);break}while(256>n);c=n<<24>>24}b.bb=c;c=b.P;d=b.bb;c.ta[c.b++]=d;c.b>=c.ja&&X(c);b.state=L(b.state);b.l=G(b.l,Qa)}b=0}if(-1==b)throw Error("corrupted input");a.Rb=da;a.kc=a.V.l;if(b||0<=N(a.V.cc,I)&&0<=N(a.V.l,a.V.cc))X(a.V.P),b=a.V.P,X(b),b.Aa=null,a.V.B.fa=null,a.Ja=0}return a.Ja}function Ia(a,b){for(;a.Na<b;++a.Na)a.ub[a.Na]=W({},3),a.vb[a.Na]=W({},3)}function Ua(a,b,c){if(!H(b,a.rb,0))return ja(a.ub[c],b);var d=8;return d=H(b,a.rb,1)?d+
(8+ja(a.Ub,b)):d+ja(a.vb[c],b)}function Ha(a){a.rb=l(2);a.ub=l(16);a.vb=l(16);a.Ub=W({},8);a.Na=0;return a}function Ja(a){y(a.rb);for(var b=0;b<a.Na;++b)y(a.ub[b].A),y(a.vb[b].A);y(a.Ub.A)}function Va(a,b){a.lb=b;var c=a.a[b].v;var d=a.a[b].o;do{if(a.a[b].C){var e=a.a[c];e.o=-1;e.C=0;a.a[c].v=c-1;a.a[b].Ea&&(a.a[c-1].C=0,a.a[c-1].v=a.a[b].Ra,a.a[c-1].o=a.a[b].Qa)}var f=c;e=d;d=a.a[f].o;c=a.a[f].v;a.a[f].o=e;a.a[f].v=b;b=f}while(0<b);a.ha=a.a[0].o;a.Y=a.a[0].v;return a.Y}function Ea(a){for(var b=0;16>
b;++b){var c,d=a.$a,e=b,f=1,g=0;for(c=d.ea;0!=c;--c){var h=e&1;e>>>=1;g+=aa(d.A[f],h);f=f<<1|h}a.Cb[b]=g}a.Bb=0}function Da(a){var b;for(b=4;128>b;++b){var c=sa(b);var d=(c>>1)-1;var e=(2|c&1)<<d;var f=b-e;for(var g=1,h=0;0!=d;--d){var k=f&1;f>>>=1;h+=v[((a.nb[e-c-1+g]-k^-k)&2047)>>>2];g=g<<1|k}a.ec[b]=h}for(e=0;4>e;++e){b=a.Ga[e];f=e<<6;for(c=0;c<a.Gb;++c)a.ya[f+c]=ka(b,c);for(c=14;c<a.Gb;++c)a.ya[f+c]+=(c>>1)-1-4<<6;c=128*e;for(b=0;4>b;++b)a.eb[c+b]=a.ya[f+b];for(;128>b;++b)a.eb[c+b]=a.ya[f+sa(b)]+
a.ec[b]}a.Lb=0}function pa(a,b){Ta(a);var c=b&a.T;a.gc&&(r(a.h,a.G,(a.i<<4)+c,1),r(a.h,a.M,a.i,0),a.i=7>a.i?7:10,ra(a.va,a.h,0,c),Z(a.Ga[ha(2)],a.h,63),Ra(a.h,67108863,26),Sa(a.$a,a.h,15));for(c=0;5>c;++c)ta(a.h)}function bb(a,b){var c,d,e,f,g,h,k,n;if(a.lb!=a.Y){var t=a.a[a.Y].v-a.Y;a.ha=a.a[a.Y].o;a.Y=a.a[a.Y].v;return t}a.Y=a.lb=0;if(a.jb){var m=a.Kb;a.jb=0}else m=qa(a);t=a.wa;var l=Y(a.f)+1;if(2>l)return a.ha=-1,1;for(c=d=0;4>c;++c)a.g[c]=a.N[c],a.R[c]=P(a.f,-1,a.g[c],273),a.R[c]>a.R[d]&&(d=c);
if(a.R[d]>=a.H){a.ha=d;t=a.R[d];var y=t-1;0<y&&(Na(a.f,y),a.I+=y);return t}if(m>=a.H)return a.ha=a.K[t-1]+4,t=m-1,0<t&&(Na(a.f,t),a.I+=t),m;var q=F(a.f,-1);var x=F(a.f,-a.N[0]-1-1);if(2>m&&q!=x&&2>a.R[d])return a.ha=-1,1;a.a[0].Sa=a.i;var w=b&a.T;a.a[1].j=v[a.G[(a.i<<4)+w]>>>2]+la(Q(a.ga,b,a.za),7<=a.i,x,q);var u=a.a[1];u.o=-1;u.C=0;u=v[2048-a.G[(a.i<<4)+w]>>>2];var A=u+v[2048-a.M[a.i]>>>2];if(x==q){c=a.i;var r=A+(v[a.ia[c]>>>2]+v[a.ua[(c<<4)+w]>>>2]);r<a.a[1].j&&(a.a[1].j=r,c=a.a[1],c.o=0,c.C=0)}d=
m>=a.R[d]?m:a.R[d];if(2>d)return a.ha=a.a[1].o,1;a.a[1].v=0;a.a[0].qa=a.g[0];a.a[0].ra=a.g[1];a.a[0].sa=a.g[2];a.a[0].Ca=a.g[3];c=d;do a.a[c--].j=268435455;while(2<=c);for(c=0;4>c;++c)if(r=a.R[c],!(2>r)){var D=A+R(a,c,a.i,w);do{var z=D+a.U.Z[272*w+(r-2)];var p=a.a[r];z<p.j&&(p.j=z,p.v=0,p.o=c,p.C=0)}while(2<=--r)}u+=v[a.M[a.i]>>>2];c=2<=a.R[0]?a.R[0]+1:2;if(c<=m){for(A=0;c>a.K[A];)A+=2;for(;m=a.K[A+1],z=u+Wa(a,m,c,w),p=a.a[c],z<p.j&&(p.j=z,p.v=0,p.o=m+4,p.C=0),c!=a.K[A]||(A+=2,A!=t);++c);}for(m=0;;){++m;
if(m==d)return Va(a,m);D=qa(a);t=a.wa;if(D>=a.H)return a.Kb=D,a.jb=1,Va(a,m);++b;u=a.a[m].v;a.a[m].C?(--u,a.a[m].Ea?(c=a.a[a.a[m].Ra].Sa,c=4>a.a[m].Qa?7>c?8:11:7>c?7:10):c=a.a[u].Sa,c=L(c)):c=a.a[u].Sa;u==m-1?c=a.a[m].o?L(c):7>c?9:11:(a.a[m].C&&a.a[m].Ea?(u=a.a[m].Ra,w=a.a[m].Qa,c=7>c?8:11):(w=a.a[m].o,c=4>w?7>c?8:11:7>c?7:10),u=a.a[u],4>w?w?1==w?(a.g[0]=u.ra,a.g[1]=u.qa,a.g[2]=u.sa,a.g[3]=u.Ca):2==w?(a.g[0]=u.sa,a.g[1]=u.qa,a.g[2]=u.ra,a.g[3]=u.Ca):(a.g[0]=u.Ca,a.g[1]=u.qa,a.g[2]=u.ra,a.g[3]=u.sa):
(a.g[0]=u.qa,a.g[1]=u.ra,a.g[2]=u.sa,a.g[3]=u.Ca):(a.g[0]=w-4,a.g[1]=u.qa,a.g[2]=u.ra,a.g[3]=u.sa));a.a[m].Sa=c;a.a[m].qa=a.g[0];a.a[m].ra=a.g[1];a.a[m].sa=a.g[2];a.a[m].Ca=a.g[3];u=a.a[m].j;q=F(a.f,-1);x=F(a.f,-a.g[0]-1-1);w=b&a.T;z=u+v[a.G[(c<<4)+w]>>>2]+la(Q(a.ga,b,F(a.f,-2)),7<=c,x,q);l=a.a[m+1];p=0;z<l.j&&(l.j=z,l.v=m,l.o=-1,l.C=0,p=1);u+=v[2048-a.G[(c<<4)+w]>>>2];A=u+v[2048-a.M[c]>>>2];x!=q||l.v<m&&!l.o||(r=A+(v[a.ia[c]>>>2]+v[a.ua[(c<<4)+w]>>>2]),r<=l.j&&(l.j=r,l.v=m,l.o=0,l.C=0,p=1));r=Y(a.f)+
1;l=r=4095-m<r?4095-m:r;if(!(2>l)){l>a.H&&(l=a.H);if(!p&&x!=q&&(p=Math.min(r-1,a.H),p=P(a.f,0,a.g[0],p),2<=p)){var B=L(c);var C=b+1&a.T;z=z+v[2048-a.G[(B<<4)+C]>>>2]+v[2048-a.M[B]>>>2];for(e=m+1+p;d<e;)a.a[++d].j=268435455;z+=(y=a.U.Z[272*C+(p-2)],y+R(a,0,B,C));p=a.a[e];z<p.j&&(p.j=z,p.v=m+1,p.o=0,p.C=1,p.Ea=0)}x=2;for(f=0;4>f;++f)if(q=P(a.f,-1,a.g[f],l),!(2>q)){C=q;do{for(;d<m+q;)a.a[++d].j=268435455;z=A+(g=a.U.Z[272*w+(q-2)],g+R(a,f,c,w));p=a.a[m+q];z<p.j&&(p.j=z,p.v=m,p.o=f,p.C=0)}while(2<=--q);
q=C;f||(x=q+1);if(q<r&&(p=Math.min(r-1-q,a.H),p=P(a.f,q,a.g[f],p),2<=p)){B=7>c?8:11;C=b+q&a.T;z=A+(h=a.U.Z[272*w+(q-2)],h+R(a,f,c,w))+v[a.G[(B<<4)+C]>>>2]+la(Q(a.ga,b+q,F(a.f,q-1-1)),1,F(a.f,q-1-(a.g[f]+1)),F(a.f,q-1));B=L(B);C=b+q+1&a.T;z+=v[2048-a.G[(B<<4)+C]>>>2];z+=v[2048-a.M[B]>>>2];for(e=q+1+p;d<m+e;)a.a[++d].j=268435455;z+=(k=a.U.Z[272*C+(p-2)],k+R(a,0,B,C));p=a.a[m+e];z<p.j&&(p.j=z,p.v=m+q+1,p.o=0,p.C=1,p.Ea=1,p.Ra=m,p.Qa=f)}}if(D>l){D=l;for(t=0;D>a.K[t];t+=2);a.K[t]=D;t+=2}if(D>=x){for(u+=
v[a.M[c]>>>2];d<m+D;)a.a[++d].j=268435455;for(A=0;x>a.K[A];)A+=2;for(q=x;;++q)if(D=a.K[A+1],z=u+Wa(a,D,q,w),p=a.a[m+q],z<p.j&&(p.j=z,p.v=m,p.o=D+4,p.C=0),q==a.K[A]){if(q<r&&(p=Math.min(r-1-q,a.H),p=P(a.f,q,D,p),2<=p)){B=7>c?7:10;C=b+q&a.T;z=z+v[a.G[(B<<4)+C]>>>2]+la(Q(a.ga,b+q,F(a.f,q-1-1)),1,F(a.f,q-(D+1)-1),F(a.f,q-1));B=L(B);C=b+q+1&a.T;z+=v[2048-a.G[(B<<4)+C]>>>2];z+=v[2048-a.M[B]>>>2];for(e=q+1+p;d<m+e;)a.a[++d].j=268435455;z+=(n=a.U.Z[272*C+(p-2)],n+R(a,0,B,C));p=a.a[m+e];z<p.j&&(p.j=z,p.v=
m+q+1,p.o=0,p.C=1,p.Ea=1,p.Ra=m,p.Qa=D+4)}A+=2;if(A==t)break}}}}}function Wa(a,b,c,d){var e=ha(c);return(128>b?a.eb[128*e+b]:a.ya[(e<<6)+(131072>b?S[b>>6]+12:134217728>b?S[b>>16]+32:S[b>>26]+52)]+a.Cb[b&15])+a.va.Z[272*d+(c-2)]}function R(a,b,c,d){if(b){var e=v[2048-a.ia[c]>>>2];1==b?e+=v[a.Fa[c]>>>2]:(e+=v[2048-a.Fa[c]>>>2],e+=aa(a.ib[c],b-2))}else e=v[a.ia[c]>>>2],e+=v[2048-a.ua[(c<<4)+d]>>>2];return e}function qa(a){var b=0;a:{var c=a.f;var d=a.K,e,f;if(c.b+c.Ya<=c.m)var g=c.Ya;else if(g=c.m-c.b,
g<c.qb){ea(c);c=0;break a}var h=0;var k=c.b>c.S?c.b-c.S:0;var n=c.u+c.b;var l=1;var m=e=0;if(c.Da){var r=fa[c.c[n]&255]^c.c[n+1]&255;e=r&1023;r^=(c.c[n+2]&255)<<8;m=r&65535;var v=(r^fa[c.c[n+3]&255]<<5)&c.Hb}else v=c.c[n]&255^(c.c[n+1]&255)<<8;r=c.L[c.Ba+v]||0;if(c.Da){var q=c.L[e]||0;var x=c.L[1024+m]||0;c.L[e]=c.b;c.L[1024+m]=c.b;q>k&&c.c[c.u+q]==c.c[n]&&(d[h++]=l=2,d[h++]=c.b-q-1);x>k&&c.c[c.u+x]==c.c[n]&&(x==q&&(h-=2),d[h++]=l=3,d[h++]=c.b-x-1,q=x);0!=h&&q==r&&(h-=2,l=1)}c.L[c.Ba+v]=c.b;var w=
(c.J<<1)+1;var u=c.J<<1;v=f=c.ma;0!=c.ma&&r>k&&c.c[c.u+r+c.ma]!=c.c[n+c.ma]&&(d[h++]=l=c.ma,d[h++]=c.b-r-1);for(e=c.Eb;;){if(r<=k||0==e--){c.s[w]=c.s[u]=0;break}q=c.b-r;m=(q<=c.J?c.J-q:c.J-q+c.S)<<1;var y=c.u+r;x=v<f?v:f;if(c.c[y+x]==c.c[n+x]){for(;++x!=g&&c.c[y+x]==c.c[n+x];);if(l<x&&(d[h++]=l=x,d[h++]=q-1,x==g)){c.s[u]=c.s[m];c.s[w]=c.s[m+1];break}}(c.c[y+x]&255)<(c.c[n+x]&255)?(c.s[u]=r,u=m+1,r=c.s[u],f=x):(c.s[w]=r,w=m,r=c.s[w],v=x)}ea(c);c=h}a.wa=c;0<a.wa&&(b=a.K[a.wa-2],b==a.H&&(b+=P(a.f,b-
1,a.K[a.wa-1],273-b)));++a.I;return b}function Ta(a){a.f&&a.kb&&(a.f.Aa=null,a.kb=0)}function sa(a){return 2048>a?S[a]:2097152>a?S[a>>10]+20:S[a>>20]+40}function Ca(a,b){y(a.X);for(var c=0;c<b;++c)y(a.Wa[c].A),y(a.Za[c].A);y(a.gb.A)}function Xa(a,b,c,d,e){var f;var g=v[a.X[0]>>>2];var h=v[2048-a.X[0]>>>2];var k=h+v[a.X[1]>>>2];h+=v[2048-a.X[1]>>>2];for(f=0;8>f;++f){if(f>=c)return;d[e+f]=g+ka(a.Wa[b],f)}for(;16>f;++f){if(f>=c)return;d[e+f]=k+ka(a.Za[b],f-8)}for(;f<c;++f)d[e+f]=h+ka(a.gb,f-8-8)}function ra(a,
b,c,d){8>c?(r(b,a.X,0,0),Z(a.Wa[d],b,c)):(c-=8,r(b,a.X,0,1),8>c?(r(b,a.X,1,0),Z(a.Za[d],b,c)):(r(b,a.X,1,1),Z(a.gb,b,c-8)));0==--a.cb[d]&&(Xa(a,d,a.Ia,a.Z,272*d),a.cb[d]=a.Ia)}function Ba(a){a.X=l(2);a.Wa=l(16);a.Za=l(16);a.gb=U({},8);for(var b=0;16>b;++b)a.Wa[b]=U({},3),a.Za[b]=U({},3);a.Z=[];a.cb=[];return a}function Fa(a,b){for(var c=0;c<b;++c)Xa(a,c,a.Ia,a.Z,272*c),a.cb[c]=a.Ia}function Q(a,b,c){return a.ca[((b&a.wb)<<a.O)+((c&255)>>>8-a.O)]}function Pa(a,b,c){var d,e=1;for(d=7;0<=d;--d){var f=
c>>d&1;r(b,a.Ma,e,f);e=e<<1|f}}function la(a,b,c,d){var e=1,f=7,g=0;if(b)for(;0<=f;--f){var h=c>>f&1;b=d>>f&1;g+=aa(a.Ma[(1+h<<8)+e],b);e=e<<1|b;if(h!=b){--f;break}}for(;0<=f;--f)b=d>>f&1,g+=aa(a.Ma[e],b),e=e<<1|b;return g}function W(a,b){a.ea=b;a.A=l(1<<b);return a}function ja(a,b){var c,d=1;for(c=a.ea;0!=c;--c)d=(d<<1)+H(b,a.A,d);return d-(1<<a.ea)}function U(a,b){a.ea=b;a.A=l(1<<b);return a}function Z(a,b,c){var d,e=1;for(d=a.ea;0!=d;){--d;var f=c>>>d&1;r(b,a.A,e,f);e=e<<1|f}}function ka(a,b){var c,
d=1,e=0;for(c=a.ea;0!=c;){--c;var f=b>>>c&1;e+=aa(a.A[d],f);d=(d<<1)+f}return e}function Sa(a,b,c){var d,e=1;for(d=0;d<a.ea;++d){var f=c&1;r(b,a.A,e,f);e=e<<1|f;c>>=1}}function H(a,b,c){var d=b[c];var e=(a.Range>>>11)*d;if((a.F^-2147483648)<(e^-2147483648))return a.Range=e,b[c]=d+(2048-d>>>5)<<16>>16,a.Range&-16777216||(a.F=a.F<<8|O(a.fa),a.Range<<=8),0;a.Range-=e;a.F-=e;b[c]=d-(d>>>5)<<16>>16;a.Range&-16777216||(a.F=a.F<<8|O(a.fa),a.Range<<=8);return 1}function y(a){for(var b=a.length-1;0<=b;--b)a[b]=
1024}function r(a,b,c,d){var e=b[c];var f=(a.Range>>>11)*e;d?(a.W=G(a.W,M(J(f),[4294967295,0])),a.Range-=f,b[c]=e-(e>>>5)<<16>>16):(a.Range=f,b[c]=e+(2048-e>>>5)<<16>>16);a.Range&-16777216||(a.Range<<=8,ta(a))}function Ra(a,b,c){for(--c;0<=c;--c)a.Range>>>=1,1==(b>>>c&1)&&(a.W=G(a.W,J(a.Range))),a.Range&-16777216||(a.Range<<=8,ta(a))}function ta(a){var b=a.W;var c=32;var d=wa(b,c);0>b[1]&&(d=G(d,ua([2,0],63-c)));c=E(d);if(0!=c||0>N(a.W,[4278190080,0])){a.ob=G(a.ob,J(a.Ua));b=a.Db;do za(a.fa,b+c),
b=255;while(0!=--a.Ua);a.Db=E(a.W)>>>24}++a.Ua;a.W=ua(M(a.W,[16777215,0]),8)}function aa(a,b){return v[((a-b^-b)&2047)>>>2]}function Ya(a){for(var b=0,c=0,d,e,f,g=a.length,h=[],k=[];b<g;++b,++c){d=a[b]&255;if(d&128)if(192==(d&224)){if(b+1>=g)return a;e=a[++b]&255;if(128!=(e&192))return a;k[c]=(d&31)<<6|e&63}else if(224==(d&240)){if(b+2>=g)return a;e=a[++b]&255;if(128!=(e&192))return a;f=a[++b]&255;if(128!=(f&192))return a;k[c]=(d&15)<<12|(e&63)<<6|f&63}else return a;else{if(!d)return a;k[c]=d}16383==
c&&(h.push(String.fromCharCode.apply(String,k)),c=-1)}0<c&&(k.length=c,h.push(String.fromCharCode.apply(String,k)));return h.join("")}function Za(a){var b=[],c,d=0,e,f=a.length;if("object"==typeof a)return a;for(e=c=0;e<f;++e)b[c++]=a.charCodeAt(e);for(e=0;e<f;++e)a=b[e],1<=a&&127>=a?++d:d=!a||128<=a&&2047>=a?d+2:d+3;c=[];for(e=d=0;e<f;++e)a=b[e],1<=a&&127>=a?c[d++]=a<<24>>24:(!a||128<=a&&2047>=a?c[d++]=(192|a>>6&31)<<24>>24:(c[d++]=(224|a>>12&15)<<24>>24,c[d++]=(128|a>>6&63)<<24>>24),c[d++]=(128|
a&63)<<24>>24);return c}function ma(a){return a[1]+a[0]}var T="function"==typeof setImmediate?setImmediate:setTimeout,da=[4294967295,-4294967296],va=[0,-9223372036854775808],I=[0,0],Qa=[1,0],fa=function(){var a,b,c=[];for(a=0;256>a;++a){var d=a;for(b=0;8>b;++b)d=0!=(d&1)?d>>>1^-306674912:d>>>1;c[a]=d}return c}(),S=function(){var a,b,c=2,d=[0,1];for(b=2;22>b;++b){var e=1<<(b>>1)-1;for(a=0;a<e;++a,++c)d[c]=b<<24>>24}return d}(),v=function(){var a,b,c=[];for(b=8;0<=b;--b){var d=1<<9-b-1;for(a=1<<9-b;d<
a;++d)c[d]=(b<<6)+(a-d<<6>>>9-b-1)}return c}(),$a=function(){var a=[{da:16,aa:64,ba:0},{da:20,aa:64,ba:0},{da:19,aa:64,ba:1},{da:20,aa:64,ba:1},{da:21,aa:128,ba:1},{da:22,aa:128,ba:1},{da:23,aa:128,ba:1},{da:24,aa:255,ba:1},{da:25,aa:255,ba:1}];return function(b){return a[b-1]||a[6]}}();"undefined"==typeof onmessage||"undefined"!=typeof window&&"undefined"!=typeof window.document||function(){onmessage=function(a){a&&a.data&&(2==a.data.action?V.Qb(a.data.data,a.data.Ka):1==a.data.action&&V.Pb(a.data.data,
a.data.mode,a.data.Ka))}}();return{Pb:function(a,b,c,d){function e(){try{for(var a,b=(new Date).getTime();ia(f.ka.la);)if(g=ma(f.ka.la.Rb)/ma(f.ka.La),200<(new Date).getTime()-b)return d(g),T(e,0),0;d(1);a=ca(f.ka.oa);T(c.bind(null,a),0)}catch(m){c(null,m)}}var f={},g,h="undefined"==typeof c&&"undefined"==typeof d;if("function"!=typeof c){var k=c;c=d=0}d=d||function(a){"undefined"!=typeof k&&postMessage({action:3,Ka:k,result:a})};c=c||function(a,b){if("undefined"!=typeof k)return postMessage({action:1,
Ka:k,result:a,error:b})};if(h){for(f.ka=Aa({},Za(a),$a(b));ia(f.ka.la););return ca(f.ka.oa)}try{f.ka=Aa({},Za(a),$a(b)),d(0)}catch(n){return c(null,n)}T(e,0)},Qb:function(a,b,c){function d(){try{for(var a,g=0,h=(new Date).getTime();ia(e.d.la);)if(0==++g%1E3&&200<(new Date).getTime()-h)return l&&(f=ma(e.d.la.V.l)/k,c(f)),T(d,0),0;c(1);a=Ya(ca(e.d.oa));T(b.bind(null,a),0)}catch(ab){b(null,ab)}}var e={},f,g="undefined"==typeof b&&"undefined"==typeof c;if("function"!=typeof b){var h=b;b=c=0}c=c||function(a){"undefined"!=
typeof h&&postMessage({action:3,Ka:h,result:l?a:-1})};b=b||function(a,b){if("undefined"!=typeof h)return postMessage({action:2,Ka:h,result:a,error:b})};if(g){for(e.d=Ga({},a);ia(e.d.la););return Ya(ca(e.d.oa))}try{e.d=Ga({},a);var k=ma(e.d.La);var l=-1<k;c(0)}catch(t){return b(null,t)}T(d,0)}}}();this.lzma_compress=function(l){return new Promise(function(G,M){V.Pb(l,9,function(l,K){null!==l?(l instanceof Uint8Array||(l=new Uint8Array(l)),G(l)):M(K)})})};this.lzma_decompress=function(l){return new Promise(function(G,
M){V.Qb(l,function(l,K){null!==l?G(l):M(K)})})}}).call(this);
